### ISSUE TITLE
Generate QUIC tracer functions using C macros

### ISSUE THREAD

**Issue by toru** [toru/h2olog#7]
BCC currently has a limitation where USDT reader funcs cannot be called from a static helper function (https://github.com/iovisor/bcc/issues/1255). This makes it a little tricky to reduce the over-redundancy of the code. Therefore consider implementing a macro-based helper.

The ideal flow would be:

1. read and parse `quicly-probes.d`
2. call the macro with the probe name, field index, field name, and field type

Another huge benefit of this approach is that supporting future probes would become easy.

**Comment by gfx** [comment]
Done in `v2` branch.
